### ISSUE TITLE
500 error on running serverless invoke local 

### ISSUE THREAD

**Issue by QuantumInformation** [AnomalyInnovations/serverless-stack-demo-api#5]
When running

$ serverless invoke local --function create --path mocks/create-event.json
from
https://serverless-stack.com/chapters/add-a-create-note-api.html

I get

![image](https://user-images.githubusercontent.com/216566/30744934-240389d4-9f9c-11e7-9376-0959fd84af35.png)

**Comment by jayair** [comment]
@QuantumInformation Are you using multiple AWS credentials? Or do you have multiple credentials? This usually happens in that case.

**Comment by QuantumInformation** [comment]
Yeah I have 2 profiles

**Comment by jayair** [comment]
@QuantumInformation The `serverless invoke local` command does not support the `--profile` option.

Did you specify the profile in your `serverless.yml`?

**Comment by QuantumInformation** [comment]
Yup:

```
provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2
  profile: personal```

![image](https://user-images.githubusercontent.com/216566/30831954-5017f620-a241-11e7-844c-4d3148def52c.png)
and in ~/.aws/credentials:
```
[personal]
aws_access_key_id
```
